fix NPE in  Populate the :trace-redirects response field #327 PR
dakrone/clj-http pull request #341
Opened 2016-11-26 16:09 UTC by jiacai2050

In order to fix NPE in #327 , I have to update two tests dealing with redirect , since I have removed `wrap-redirects` middleware, so it is impossible for clj-http to control redirect behavior

2016-11-30 14:16 UTC, jiacai2050 commented
Any question with this PR ?

2016-12-06 21:17 UTC, dakrone requested changes
I left a comment on this, but what I'm really concerned about is that there is now no way to disable redirects. There are some cases where a redirect needs to be handled by client code (think SAML SSO) instead of by the Apache HTTP library, so I think we should still have a way to disabling redirects.

Thoughts?

2016-12-06 21:17 UTC, dakrone commented on src/clj_http/core.clj
> +     :trace-redirects (mapv #(.toString %)
I think this can just be `(mapv str (.getRedirectLocations))`

2016-12-07 01:01 UTC, jiacai2050 commented on src/clj_http/core.clj
> +     :trace-redirects (mapv #(.toString %)
yes, it's more idiomatic

2016-12-07 01:04 UTC, jiacai2050 commented
Redirect control is reasonable, We can use [RequestConfig.setRedirectsEnabled()](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/config/RequestConfig.Builder.html#setRedirectsEnabled(boolean)) method to toggle it

2016-12-09 22:36 UTC, dakrone commented
> Redirect control is reasonable, We can use RequestConfig.setRedirectsEnabled() method to toggle it.

Would you be willing to extend the PR to expose that as a boolean option?

2016-12-10 11:08 UTC, jiacai2050 commented
clj-http already has support for redirect control in [here](https://github.com/dakrone/clj-http/blob/master/src/clj_http/core.clj#L106), I add one more test case for it

2016-12-13 23:09 UTC, merged

2016-12-13 23:09 UTC, dakrone commented
Merged, thanks!

2023-11-17 23:20 UTC, mrkam2 commented
`wrap-redirect` is marked as deprecated but what's the recommended alternative API to use? Would be great to include that into the docstring in a phrase such as "Deprecated, use ... instead".